name: Pipeline
on: [push, pull_request] # ação

jobs: 
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Instalar python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Instalar poetry
        run: pipx install poetry
      - name: Instalar dependêcias
        run: poetry install 

      - name: executar test
        run: poetry run task test


