name: Pipeline
on: [push, pull_request] # ação

jobs: 
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_TIME: 30
      
    steps:
      - name: copia os arquivos do repositório
        uses: actions/checkout@v3

      - name: Instalar python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Instalar poetry
        run: pipx install poetry

      - name: Instalar dependêcias
        run: poetry install 

      - name: Debug Database URL
        run: echo "DATABASE_URL is $DATABASE_URL"

      - name: executar test
        run: poetry run task test


